using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorksCRUD.Models
{
    //Operation Type is a partial property that is used to specify save-update-delete operation in the flow between view to controller
    //This separate file is needed because models are auto generated by EF
    public partial class Department
    {
        [NotMapped]
        public string OperationType { get; set; }
    }

    public partial class Employee
    {
        [NotMapped]
        public string OperationType { get; set; }
    }

    public partial class EmployeeDepartmentHistory
    {
        [NotMapped]
        public string OperationType { get; set; }
    }
}